### ISSUE TITLE
Any interest in joining the trac-hacks organization?

### ISSUE THREAD

**Issue by rjollos** [AccelerationNet/trac-timingandestimationplugin#1]
Hi,

I'm an administrator for trac-hacks.org.  We've created an organization on GitHub and are inviting authors of trac-hacks plugins to join the organization.  Your repository could be transferred into the organization as described in the [GitHub docs](https://help.github.com/articles/transferring-a-repository/).  You'd retain full control over the repository, but the hope is that it will be easier for users on GitHub to find trac-hacks plugins, such as yours, by viewing the trac-hacks organization.

In the future, if you choose to no longer maintain the plugin, the organization would be able to provide commit access to new developers.  This would only be done with your permission, as has been the policy for plugins hosted on trac-hacks.org.  If you've already decided to no longer maintain the plugin, we would particularly appreciate you transferring the plugin to the trac-hacks organization so that we can help find new maintainers for it.

Finally, creating the trac-hacks organization is a work in progress. I appreciate if you have any suggestions on how to best support the community of trac plugin developers on GitHub. More information can be found in the [blog post](http://trac-hacks.org/blog/2015-02-21-trac-hacks-on-github).

Kind regards,
- Ryan

**Comment by bobbysmith007** [comment]
Howdy,

Sorry for the late reply, I would be happy to join the organization / move the plugin to the organization.

Most of the plugins I author are gradually being subsumed by trac and have been in maintenance mode for years, so I am not terribly active, but would be happy to assist where I can.

Cheers,
Russ

**Comment by rjollos** [comment]
Thanks, I sent you an invite. If you have any plugins you are interested in moving, please let me know. If your GitHub repositories are just development mirrors of what exists on trac-hacks.org, you may not want to move them. Eventually we'll mirror the trac-hacks.org SVN repositories to GitHub.

**Comment by bobbysmith007** [comment]
Yeah, all of my repos are already in svn on trac-hacks, so I guess I will let them get mirrored.  I just find that more and more, my workflow is centered around git and dealing with SVN is a bit tiresome.  I wanted to move this code between different servers, preferably before publishing it, thus the moving my development to git.
